In [1]:
!pip install sentence-transformers -q

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/transformers/

In [2]:
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
jobs_data = pd.read_csv("final_jobs_dataset (1).csv")
cv_data = pd.read_csv("cv_cleaned.csv")

cv_texts = cv_data['final_text'].fillna("").astype(str).tolist()
job_texts = jobs_data['job_description'].fillna("").astype(str).tolist()

print("Data Loaded ✅")
print("CVs:", len(cv_texts))
print("Jobs:", len(job_texts))

Data Loaded ✅
CVs: 3500
Jobs: 3685

In [5]:
print("CV Sample:")
print(cv_texts[0][:300])

print("\nJob Sample:")
print(job_texts[0][:300])

CV Sample:
jessica claire montgomery street san francisco ca resumesampleexamplecom professional summary highly skilled software development professional bringing years software design development integration advanced knowledge java skills agile html xml jdbc tomcat work history senior java developertech lead

Job Sample:
about hopper

at hopper, we’re on a mission to make booking travel faster, easier, and more transparent. we are leveraging the power that comes from combining massive amounts of data and machine learning to build the world’s fastest-growing travel app -- one that enables our customers to save money

In [6]:
bert_model = SentenceTransformer('all-MiniLM-L6-v2')

d:\New folder (6)\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lenovo\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

In [7]:
cv_embeddings_bert = bert_model.encode(
    cv_texts,
    show_progress_bar=True,
    convert_to_numpy=True
)

job_embeddings_bert = bert_model.encode(
    job_texts,
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches: 100%|██████████| 110/110 [01:08<00:00,  1.61it/s]
Batches: 100%|██████████| 116/116 [01:02<00:00,  1.86it/s]

In [8]:
print("CV Embeddings Shape:", cv_embeddings_bert.shape)
print("Job Embeddings Shape:", job_embeddings_bert.shape)

CV Embeddings Shape: (3500, 384)
Job Embeddings Shape: (3685, 384)

In [9]:
similarity_matrix_bert = cosine_similarity(
    cv_embeddings_bert,
    job_embeddings_bert
)

In [10]:
print("Similarity Matrix Shape:", similarity_matrix_bert.shape)
print("Higher score = better semantic match between CV and Job Description")

Similarity Matrix Shape: (3500, 3685)
Higher score = better semantic match between CV and Job Description

In [11]:
for i in range(3):
    top_jobs = np.argsort(similarity_matrix_bert[i])[::-1][:5]

    print(f"\nCV {i} recommendations:")

    for j in top_jobs:
        print("Job:", jobs_data.iloc[j]['job_title'])
        print("Score:", similarity_matrix_bert[i][j])
        print("-"*30)

CV 0 recommendations:
Job: data modeler/data analyst
Score: 0.5950824
------------------------------
Job: senior data engineer
Score: 0.5731243
------------------------------
Job: it data engineer
Score: 0.5712783
------------------------------
Job: sr data analyst
Score: 0.5624286
------------------------------
Job: big data engineer
Score: 0.55635226
------------------------------

CV 1 recommendations:
Job: data scientist
Score: 0.5761539
------------------------------
Job: data modeler/data analyst
Score: 0.5400808
------------------------------
Job: data science & machine learning
Score: 0.53706676
------------------------------
Job: java with big data engineer
Score: 0.5138591
------------------------------
Job: informatica data modeler
Score: 0.5078175
------------------------------

CV 2 recommendations:
Job: data science & machine learning
Score: 0.65975577
------------------------------
Job: principal data engineer
Score: 0.62493575
------------------------------
Job: java with big data engineer
Score: 0.61422145
------------------------------
Job: big-data engineer
Score: 0.5979556
------------------------------
Job: big data engineer ii
Score: 0.57874477
------------------------------

In [12]:
print("Top-5 jobs retrieved successfully for each CV ✅")

Top-5 jobs retrieved successfully for each CV ✅

In [13]:
i = 0
top_jobs = np.argsort(similarity_matrix_bert[i])[::-1][:5]

df_results = pd.DataFrame({
    "Recommended Job": [jobs_data.iloc[j]['job_title'] for j in top_jobs],
    "Match Score": [f"{similarity_matrix_bert[i][j]*100:.2f}%" for j in top_jobs],
    "Description Preview": [jobs_data.iloc[j]['job_description'][:100] + "..." for j in top_jobs]
})

df_results

,Recommended Job,Match Score,Description Preview
0,data modeler/data analyst,59.51%,job description:\n\n· bs/ba degree with 6+ yea...
1,senior data engineer,57.31%,role: senior data engineer\n\njob type: contra...
2,it data engineer,57.13%,this customer is the world's largest manufactu...
3,sr data analyst,56.24%,my direct client in center city philadelphia i...
4,big data engineer,55.64%,title: software engineering - big data\nlocati...

In [14]:
top_5_scores = similarity_matrix_bert[i][top_jobs]
print("Average Top-5 Match Score:", top_5_scores.mean())

Average Top-5 Match Score: 0.5716532

In [15]:
np.save("cv_embeddings_bert.npy", cv_embeddings_bert)
np.save("job_embeddings_bert.npy", job_embeddings_bert)

print("Embeddings saved successfully ✅")

Embeddings saved successfully ✅

In [16]:
import numpy as np

cv_embeddings = np.load("cv_embeddings_bert.npy")
job_embeddings = np.load("job_embeddings_bert.npy")

In [17]:
print(cv_embeddings.shape)
print(job_embeddings.shape)

(3500, 384)
(3685, 384)

In [18]:
print(cv_embeddings[0])

[ 5.08641712e-02 -7.60697350e-02 -2.93945931e-02  1.54265175e-02
 -2.18714662e-02 -1.91713106e-02 -7.08138347e-02  1.12828715e-02
 -1.08519897e-01  2.46648081e-02 -3.85322906e-02 -2.08712779e-02
  3.90019454e-02 -7.21972734e-02  9.00117755e-02  3.45093422e-02
  6.08565547e-02 -4.45139557e-02  1.18823219e-02 -6.19954728e-02
 -1.53927803e-02 -2.18234677e-02 -5.92300855e-02 -5.94187453e-02
 -2.32127421e-02  2.30828617e-02 -2.00659651e-02  1.27888639e-02
 -7.64433667e-02 -6.23257756e-02 -9.66318250e-02  8.34942088e-02
  8.68145600e-02  8.11704844e-02  5.67089766e-02  8.33690539e-02
 -4.24849428e-02  7.22491816e-02  5.14466390e-02 -3.80317792e-02
 -1.58511668e-01 -1.15875741e-02 -5.50862141e-02 -1.92213953e-02
 -4.02420247e-03 -1.00622945e-01 -7.35876039e-02 -9.35739428e-02
  4.09036130e-02  3.30038480e-02 -9.15548205e-02 -2.57579274e-02
  8.26113075e-02 -2.30107037e-03 -1.31580131e-02  1.50555270e-02
  1.54551468e-03 -3.06973904e-02 -6.43768832e-02 -4.67204079e-02
 -4.46727872e-02  1.04356622e-02 -3.31030525e-02  1.01573151e-02
 -5.82160652e-02  2.04095338e-02 -8.17677006e-02  5.57294376e-02
 -2.80658938e-02 -1.11986451e-01 -2.01517600e-03 -4.14010063e-02
 -1.00959443e-01  8.46116021e-02  3.38673033e-03 -1.25434073e-02
  5.74714690e-02  2.52336431e-02  7.70311728e-02 -7.66402250e-03
 -2.70947050e-02  2.74081007e-02 -1.09618574e-01  6.15533851e-02
 -1.35226935e-01  4.21931334e-02  3.41222361e-02  4.74469401e-02
  6.00346662e-02  1.65146887e-02  4.51121101e-04  2.31499635e-02
 -1.86519371e-03 -3.73530500e-02  1.11930817e-02 -7.55594075e-02
  2.76015662e-02 -3.09006218e-02 -6.64547598e-03  2.95149181e-02
 -2.36584004e-02  1.20653315e-02  8.03101808e-02 -3.20711695e-02
 -7.76549280e-02 -5.01693599e-03  8.93839672e-02  5.18621802e-02
  6.97677583e-03 -2.31661256e-02  1.17942262e-02 -3.26966750e-04
 -1.35215402e-01 -7.76764899e-02 -2.46396475e-02 -4.99841832e-02
 -4.97453511e-02  3.43203209e-02  4.94172610e-03  7.14109167e-02
  3.68909352e-02  7.01483712e-02 -3.12917866e-02 -1.82946445e-03
  2.59169154e-02  5.34513034e-02 -7.64182061e-02  3.23942557e-32
 -2.59003956e-02  4.87585329e-02  2.28719637e-02  2.27930918e-02
  1.87985413e-02 -4.99764420e-02  3.61213014e-02  3.97837125e-02
 -1.14869006e-01 -5.71709014e-02  4.97847572e-02  5.36795072e-02
  1.68244261e-02  3.83195765e-02  1.64224021e-02 -5.54430438e-03
 -1.52054355e-02 -2.17122659e-02 -4.12340052e-02  1.89410821e-02
  3.83381397e-02 -1.93167105e-02  1.73313972e-02 -2.77516712e-02
 -3.74267111e-03 -3.80082764e-02  1.43828234e-02  4.12580520e-02
  6.52298778e-02  3.34276780e-02  5.61644211e-02 -2.77412143e-02
 -4.21756804e-02 -2.45197862e-02  2.54814085e-02  6.07630759e-02
  3.92721109e-02 -5.68260998e-02  7.03561008e-02 -8.56277533e-03
 -7.29335025e-02  3.12995464e-02  2.04434153e-02 -1.11609856e-02
  1.26484863e-03 -3.95343378e-02  1.00716330e-01 -4.37758258e-03
  4.49996144e-02 -5.27355336e-02 -6.76303729e-02  2.03459859e-02
  5.22243418e-02  9.20147300e-02  2.03876980e-02  2.09750254e-02
  6.15708716e-02 -2.08710842e-02  9.31556895e-03  6.69735000e-02
 -1.19594477e-01  9.03147832e-03 -2.68556736e-02 -1.81384273e-02
 -9.74605209e-04 -2.31815632e-02  5.82127646e-02  6.85045077e-03
  9.39998776e-02  6.80801570e-02 -7.67000252e-03 -5.44528477e-02
  7.53623247e-02  7.16762841e-02 -4.75781411e-02  1.49241451e-03
 -3.97159308e-02 -8.53747223e-03  3.22185382e-02 -1.92099474e-02
 -4.01619188e-02 -1.31832017e-02 -5.02148941e-02  4.44164313e-02
  1.19335920e-01  4.21509333e-02  1.54208858e-02 -3.06536183e-02
 -2.40170192e-02  1.05407350e-02  1.74892768e-02 -1.85832866e-02
 -5.33553632e-03  2.92040631e-02 -5.14063686e-02 -3.19429099e-32
 -6.37056231e-02  4.15096572e-03 -2.94414442e-02  1.81880891e-02
  9.10153538e-02 -3.00140139e-02  1.93456151e-02 -7.82928690e-02
  1.60430875e-02 -1.99876744e-02 -2.21187361e-02 -1.47262886e-02
 -6.37986958e-02  1.08977947e-02 -2.86513679e-02  1.69299170e-02
 -3.40691544e-02  1.44710429e-02 -6.10504039e-02  3.49282473e-02
  2.33983053e-04  3.58822085e-02 -3.10542919e-02  3.62229720e-02
  7.36190751e-02  1.50897987e-02 -8.91657546e-02  6.40984625e-03
  4.44926545e-02 -2.13835649e-02 -2.49050055e-02 -4.89147231e-02
 -6.30361065e-02  3.13566774e-02 -3.29658086e-03 -2.36623902e-02
 -5.42150531e-03 -3.76254506e-02 -1.68219432e-02  5.78752756e-02
  6.29622340e-02 -8.15644860e-02 -7.56263966e-03 -7.39088468e-03
 -3.27070542e-02 -4.75762114e-02 -1.04886509e-01 -5.56245483e-02
 -3.66214924e-02 -3.19724791e-02 -4.93975878e-02  3.04066427e-02
 -7.26322830e-02 -2.23292820e-02  2.01156288e-02 -8.68956000e-02
  8.62616375e-02 -3.81640568e-02 -6.46695867e-02 -3.97044010e-02
  2.38989542e-05  1.33844158e-02  5.69351129e-02  7.19712153e-02
  4.76083718e-02 -9.87695009e-02  1.96899909e-05 -1.12933265e-02
 -1.66682884e-01 -6.21104799e-02 -3.78846861e-02 -1.49682844e-02
 -8.37951824e-02 -8.32063705e-02 -4.62857634e-02  7.48756900e-02
 -4.80844192e-02 -3.22904550e-02 -3.68157029e-02  2.53031366e-02
 -2.79251244e-02 -2.56028473e-02 -3.14284451e-02  3.07939909e-02
 -2.91255452e-02  5.95265403e-02 -2.84426231e-02  6.81460230e-03
 -6.02211058e-03  9.85861383e-03 -1.09608829e-01 -8.21227208e-02
 -2.17104480e-02  2.09273677e-02 -2.28010919e-02 -8.84736480e-08
 -4.67429496e-02  3.50087807e-02 -3.85236852e-02  4.54616100e-02
  7.90244639e-02  3.21394391e-02 -5.96663989e-02  6.69608936e-02
  2.74308715e-02  3.10395975e-02  3.59876221e-03 -2.22486202e-02
  4.50869370e-03 -2.13820264e-02  1.00693777e-01  3.12712006e-02
 -4.90287133e-02  3.36236842e-02 -4.76147756e-02 -7.36109987e-02
  2.62920372e-02  2.01623309e-02 -9.32455361e-02  6.03874102e-02
 -2.31280588e-02 -4.24273647e-02 -5.28218150e-02  7.92650972e-03
 -5.10371150e-03 -3.09098940e-02  1.32100070e-02 -2.48840824e-02
 -3.76004055e-02 -6.78852946e-02  1.60183683e-01 -8.78897775e-03
  1.39189800e-02 -2.15190370e-03  3.31660658e-02  3.99887748e-02
 -4.97274883e-02  1.49391592e-02  1.23822978e-02  5.07258065e-02
  2.65217051e-02  3.20581608e-02 -1.24060534e-01  3.23427208e-02
  9.93186701e-03 -1.14476547e-01 -2.22170670e-02 -4.62908410e-02
 -4.39420752e-02  4.75704408e-04  2.92286091e-02  9.82116535e-02
 -2.25897245e-02  1.49017805e-02  5.04040308e-02  1.83219239e-02
  5.10797165e-02 -3.54718715e-02 -4.57838997e-02  4.05643368e-03]

In [19]:
print(cv_embeddings[0][:10])

[ 0.05086417 -0.07606973 -0.02939459  0.01542652 -0.02187147 -0.01917131
 -0.07081383  0.01128287 -0.1085199   0.02466481]

In [20]:
import pandas as pd

df_emb = pd.DataFrame(cv_embeddings)
df_emb.head()

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.050864,-0.076070,-0.029395,0.015427,-0.021871,-0.019171,-0.070814,0.011283,-0.108520,0.024665,...,0.029229,0.098212,-0.022590,0.014902,0.050404,0.018322,0.051080,-0.035472,-0.045784,0.004056
1,0.048936,-0.044995,-0.028675,-0.069765,-0.027521,-0.046056,0.009065,0.044963,-0.077154,0.042421,...,0.042603,0.064457,0.004688,0.070380,0.049006,-0.012808,0.084342,0.000968,0.001448,0.020021
2,-0.048309,-0.041490,-0.007161,0.027420,-0.026790,-0.011672,-0.062471,-0.006510,-0.092823,0.040452,...,0.038938,0.123432,0.063805,-0.017433,0.099677,0.025767,0.044352,-0.065372,-0.014411,0.027591
3,0.011886,-0.071153,-0.027228,0.044289,-0.062909,-0.031058,-0.012409,-0.004627,-0.117843,-0.023648,...,0.025476,0.081046,0.017459,0.036306,0.054697,0.063012,0.065934,0.011802,-0.009865,0.002399
4,0.022853,-0.053448,-0.031811,0.020541,-0.057424,-0.037365,0.007573,0.013839,-0.118231,-0.005468,...,0.016906,0.106030,0.013072,0.075341,0.090544,0.041729,0.085790,0.022726,-0.042125,-0.003396